### PR TITLE
Added a possibility to set timeouts

### PR DESCRIPTION
**Pull request by iampeter**

### CODE REVIEW

**Comment by TheKiteEatingTree** [comment]
This PR looks great!  Thanks!  Noticed 1 unused function in CordovaHttpPlugin.java.  Can you delete that?

My only other concern is what does a timeout of 0 mean?  If it means anything other than use default timeout values then it should not be the default.

Would love if this supported iOS too, but will still accept it for just Android.

**Comment by iampeter** [comment]
Well 0 means 'default socket values', but maybe the description is misleading - it's supposed to say what the default Android ones are.

So you would like to set plugins defaults to other values than the Java defaults?

**Comment by TheKiteEatingTree** [comment]
No, I want it to be the default Java timeouts.  Does Java really wait forever by default?

**Comment by iampeter** [comment]
Yes, it waits forever.

**Comment by iampeter** [comment]
Do you plan to merge this request?

**Comment by Fmstrat** [comment]
+1

I too would like this merged. It's unfortunate that it wasn't done sooner, as I've submitted a pull request to support TLSv1.1 and 1.2 that may not be able to be automatically merged after this one because of the delay on this pull.

**Comment by fodi2** [comment]
Any news on this pull request? I'd love to use this feature.

**Comment by yyfearth** [comment]
Definitely need such a function to have a default timeout, and also could allow us to specify a timeout manually.

**Pull request closed without merging**
