### PR TITLE
Adds support for PostJSON, PUT and DELETE methods

### PR DESCRIPTION
**Pull request by ghost**
Adds support for PostJSON, PUT and DELETE methods

### CODE REVIEW

**Comment by ihadeed** [comment]
hey @spuentesp 

thanks for the awesome work

I just tested this but it failed at compile time

here's the log output I got:

```


/home/ibby/work/myproject/platforms/android/src/com/synconset/CordovaHttpPlugin.java:80: error: cannot find symbol
            CordovaHttpDelete delete = new CordovaHttpDelete(urlString, paramsMap, headersMap, callbackContext);
            ^
  symbol:   class CordovaHttpDelete
  location: class CordovaHttpPlugin
/home/ibby/work/myproject/platforms/android/src/com/synconset/CordovaHttpPlugin.java:80: error: cannot find symbol
            CordovaHttpDelete delete = new CordovaHttpDelete(urlString, paramsMap, headersMap, callbackContext);
                                           ^
  symbol:   class CordovaHttpDelete
  location: class CordovaHttpPlugin
/home/ibby/work/myproject/platforms/android/src/com/synconset/CordovaHttpPlugin.java:96: error: cannot find symbol
            CordovaHttpPut put = new CordovaHttpPut(urlString, jsonObj, headersMap, callbackContext);
            ^
  symbol:   class CordovaHttpPut
  location: class CordovaHttpPlugin
/home/ibby/work/myproject/platforms/android/src/com/synconset/CordovaHttpPlugin.java:96: error: cannot find symbol
            CordovaHttpPut put = new CordovaHttpPut(urlString, jsonObj, headersMap, callbackContext);
                                     ^
  symbol:   class CordovaHttpPut
  location: class CordovaHttpPlugin

/home/ibby/work/myproject/platforms/android/src/com/synconset/CordovaHttpPlugin.java:103: error: cannot find symbol
            CordovaHttpPostJson postJson = new CordovaHttpPostJson(urlString, jsonObj, headersMap, callbackContext);

            ^

  symbol:   class CordovaHttpPostJson

  location: class CordovaHttpPlugin

/home/ibby/work/myproject/platforms/android/src/com/synconset/CordovaHttpPlugin.java:103: error: cannot find symbol

            CordovaHttpPostJson postJson = new CordovaHttpPostJson(urlString, jsonObj, headersMap, callbackContext);

                                               ^

  symbol:   class CordovaHttpPostJson

  location: class CordovaHttpPlugin

Note: Some input files use or override a deprecated API.

Note: Recompile with -Xlint:deprecation for details.

Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.

6 errors
```

Running on Ubuntu 16.04
Cordova 6.3.1
Cordova Android 5.1.1

**Comment by ghost** [comment]
Hi,

I've tried replicating the error, with no success.

Delete: Entry, ":NSAppTransportSecurity", Does Not Exist

File Doesn't Exist, Will Create: platforms/ios/_/_-Info.plist

Delete: Entry, ":NSAppTransportSecurity:NSAllowsArbitraryLoads", Does Not Exist

File Doesn't Exist, Will Create: platforms/ios/_/_-Info.plist

File Doesn't Exist, Will Create: platforms/ios/_/_-Info.plist

File Doesn't Exist, Will Create: platforms/ios/_/_-Info.plist

grep: platforms/ios/MiMovistar/Classes/AppDelegate.m: No such file or directory

Not there

/Users/rodrigopalmafanjul/appmimovistar/i+d/hooks/before_build/ios_before_build.sh: line 25: platforms/ios/MiMovistar/Classes/AppDelegate.m: No such file or directory

Delete: Entry, ":CFBundleLocalizations", Does Not Exist

File Doesn't Exist, Will Create: platforms/ios/_/_-Info.plist

File Doesn't Exist, Will Create: platforms/ios/_/_-Info.plist

File Doesn't Exist, Will Create: platforms/ios/_/_-Info.plist

Running command: /Users/rodrigopalmafanjul/appmimovistar/i+d/hooks/after_prepare/010_add_platform_class.js /Users/rodrigopalmafanjul/appmimovistar/i+d

add to body class: platform-android

ANDROID_HOME=/usr/local/Cellar/android-sdk/24.4.1_1

JAVA_HOME=/Library/Java/JavaVirtualMachines/jdk1.8.0_92.jdk/Contents/Home

Starting a new Gradle Daemon for this build (subsequent builds will be faster).

Incremental java compilation is an incubating feature.

:preBuild

UP-TO-DATE

:preDebugBuild

UP-TO-DATE

:checkDebugManifest

:CordovaLib:preBuild

UP-TO-DATE
:CordovaLib:preDebugBuild

UP-TO-DATE

:CordovaLib:compileDebugNdk

UP-TO-DATE

:CordovaLib:compileLint

:CordovaLib:copyDebugLint

UP-TO-DATE
:CordovaLib:mergeDebugProguardFiles

UP-TO-DATE

:CordovaLib:packageDebugRenderscript

UP-TO-DATE

:CordovaLib:checkDebugManifest

:CordovaLib:prepareDebugDependencies

:CordovaLib:compileDebugRenderscript

UP-TO-DATE

:CordovaLib:generateDebugResValues

UP-TO-DATE

:CordovaLib:generateDebugResources

UP-TO-DATE

:CordovaLib:packageDebugResources

UP-TO-DATE

:CordovaLib:compileDebugAidl

UP-TO-DATE

:CordovaLib:generateDebugBuildConfig

UP-TO-DATE

:CordovaLib:mergeDebugShaders

UP-TO-DATE

:CordovaLib:compileDebugShaders

UP-TO-DATE

:CordovaLib:generateDebugAssets

UP-TO-DATE

:CordovaLib:mergeDebugAssets

UP-TO-DATE

:CordovaLib:processDebugManifest

UP-TO-DATE

:CordovaLib:processDebugResources

UP-TO-DATE

:CordovaLib:generateDebugSources

UP-TO-DATE

:CordovaLib:incrementalDebugJavaCompilationSafeguard

UP-TO-DATE

:CordovaLib:compileDebugJavaWithJavac

UP-TO-DATE

:CordovaLib:processDebugJavaRes

UP-TO-DATE

:CordovaLib:transformResourcesWithMergeJavaResForDebug

UP-TO-DATE

:CordovaLib:transformClassesAndResourcesWithSyncLibJarsForDebug

UP-TO-DATE

:CordovaLib:mergeDebugJniLibFolders

UP-TO-DATE

:CordovaLib:transformNative_libsWithMergeJniLibsForDebug

UP-TO-DATE

:CordovaLib:transformNative_libsWithSyncJniLibsForDebug

UP-TO-DATE

:CordovaLib:bundleDebug

UP-TO-DATE

:prepareAndroidCordovaLibUnspecifiedDebugLibrary

UP-TO-DATE

:preReleaseBuild

UP-TO-DATE

:CordovaLib:preReleaseBuild

UP-TO-DATE

:CordovaLib:compileReleaseNdk

UP-TO-DATE
:CordovaLib:copyReleaseLint
 UP-TO-DATE

:CordovaLib:mergeReleaseProguardFiles

UP-TO-DATE

:CordovaLib:packageReleaseRenderscript

UP-TO-DATE

:CordovaLib:checkReleaseManifest

:CordovaLib:prepareReleaseDependencies

:CordovaLib:compileReleaseRenderscript

UP-TO-DATE
:CordovaLib:generateReleaseResValues

UP-TO-DATE

:CordovaLib:generateReleaseResources
 UP-TO-DATE

:CordovaLib:packageReleaseResources
 UP-TO-DATE
:CordovaLib:compileReleaseAidl
 UP-TO-DATE
:CordovaLib:generateReleaseBuildConfig
 UP-TO-DATE
:CordovaLib:mergeReleaseShaders UP-TO-DATE
:CordovaLib:compileReleaseShaders UP-TO-DATE
:CordovaLib:generateReleaseAssets UP-TO-DATE

:CordovaLib:mergeReleaseAssets
 UP-TO-DATE

:CordovaLib:processReleaseManifest
 UP-TO-DATE
:CordovaLib:processReleaseResources
 UP-TO-DATE
:CordovaLib:generateReleaseSources UP-TO-DATE
:CordovaLib:incrementalReleaseJavaCompilationSafeguard
 UP-TO-DATE
:CordovaLib:compileReleaseJavaWithJavac
 UP-TO-DATE

:CordovaLib:processReleaseJavaRes
 UP-TO-DATE
:CordovaLib:transformResourcesWithMergeJavaResForRelease
 UP-TO-DATE
:CordovaLib:transformClassesAndResourcesWithSyncLibJarsForRelease UP-TO-DATE
:CordovaLib:mergeReleaseJniLibFolders UP-TO-DATE
:CordovaLib:transformNative_libsWithMergeJniLibsForRelease
 UP-TO-DATE
:CordovaLib:transformNative_libsWithSyncJniLibsForRelease
 UP-TO-DATE

:CordovaLib:bundleRelease UP-TO-DATE

:prepareComAndroidSupportSupportCompat2421Library
 UP-TO-DATE
:prepareComAndroidSupportSupportCoreUi2421Library
 UP-TO-DATE
:prepareComAndroidSupportSupportCoreUtils2421Library
 UP-TO-DATE

:prepareComAndroidSupportSupportFragment2421Library
 UP-TO-DATE
:prepareComAndroidSupportSupportMediaCompat2421Library
 UP-TO-DATE
:prepareComAndroidSupportSupportV42421Library

UP-TO-DATE
:prepareComGoogleAndroidGmsPlayServicesBase940Library
 UP-TO-DATE

:prepareComGoogleAndroidGmsPlayServicesBasement940Library

UP-TO-DATE

:prepareComGoogleAndroidGmsPlayServicesLocation940Library
 UP-TO-DATE
:prepareComGoogleAndroidGmsPlayServicesTasks940Library
 UP-TO-DATE

:prepareDebugDependencies

:compileDebugAidl

:compileDebugRenderscript

:generateDebugBuildConfig
 UP-TO-DATE

:mergeDebugShaders
 UP-TO-DATE

:compileDebugShaders
 UP-TO-DATE

:generateDebugAssets
 UP-TO-DATE

:mergeDebugAssets

:generateDebugResValues

UP-TO-DATE

:generateDebugResources

:mergeDebugResources

:processDebugManifest

:processDebugResources

:generateDebugSources

:incrementalDebugJavaCompilationSafeguard

UP-TO-DATE
:compileDebugJavaWithJavac
Note: /Users/rodrigopalmafanjul/appmimovistar/i+d/platforms/android/src/org/apache/cordova/file/DirectoryManager.java uses or overrides a deprecated API.

Note: Recompile with -Xlint:deprecation for details.
Note: /Users/rodrigopalmafanjul/appmimovistar/i+d/platforms/android/src/org/apache/cordova/file/AssetFilesystem.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.

Incremental compilation of 23 classes completed in 1.621 secs.

:compileDebugNdk

UP-TO-DATE
:compileDebugSources

:prePackageMarkerForDebug

:transformClassesWithDexForDebug

To run dex in process, the Gradle daemon needs a larger heap.
It currently has approximately 910 MB.
For faster builds, increase the maximum heap size for the Gradle daemon to more than 2048 MB.
To do this set org.gradle.jvmargs=-Xmx2048M in the project gradle.properties.
For more information see https://docs.gradle.org/current/userguide/build_environment.html

:mergeDebugJniLibFolders
 UP-TO-DATE

:transformNative_libsWithMergeJniLibsForDebug

UP-TO-DATE

:processDebugJavaRes
 UP-TO-DATE
:transformResourcesWithMergeJavaResForDebug
 UP-TO-DATE
:validateDebugSigning
:packageDebug

:zipalignDebug

:assembleDebug

:cdvBuildDebug

BUILD SUCCESSFUL

Total time: 1 mins 46.587 secs

Built the following apk(s): 
    /Users/rodrigopalmafanjul/appmimovistar/i+d/platforms/android/build/outputs/apk/android-debug.apk

Running on macOS Sierra 10.12
Cordova 6.3.1
Cordova Android 5.2.2

**Comment by ihadeed** [comment]
Thanks for the quick response, I managed to get another fork running for now.

But I will test your fork again with Cordova Android 5.2.2 .. maybe the problem only happens with 5.1.1

**Comment by KerryRitter** [comment]
I need this as soon as we can get it :)

**Comment by musahaidari** [comment]
Thank you for the awesome work. We need it very urgently to be merged with master too.

**Comment by ghost** [comment]
Hi everyone, does this fails to build with some cordova version? i've tried to replicate errors, with no success.

i will update my branch anyway, if anyone wants to use it for the time being.

**Comment by musahaidari** [comment]
For newbies like me: I had some problem integrating this to my project, so I had a research on how to do it. You can find the way to do that here:

http://stackoverflow.com/questions/43575839/how-to-send-http-put-request-using-ionic2-native-http-plugin

**Comment by JohnKimDev** [comment]
any update on this?

**Comment by eluzardo-simpro** [comment]
Any update on this guys? :)

**Comment by mlarrieur** [comment]
@eluzardo-simpro You can use my fork https://github.com/miki95/cordova-HTTP where is already implemented

**Pull request closed without merging**
